config/routes.rb
Rails.application.routes.draw do

  resources :destinations
  root 'welcom#index'

  get 'index' => 'welcom#index'

  get 'params' => 'welcom#about_params'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ActiveRecord::Base
   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    if params[:country] == nil
    @destinations = Destination.all
  else
    @destinations = Destination.where(country: params[:country].titleize)
  end
    @my_countries = Destination.select(:country).order(:country).distinct
end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :population, :avatar)
    end
end

app/controllers/welcom_controller.rb
class WelcomController < ApplicationController
  def index
    @homeland = "Georgia, USA"
    @countries = ['Bahamas', 'Brazil', 'Columbia', 'Costa Rica' ]
    @travel_pictures = ["costarica.jpeg", "bahamas-nassau-downtown.jpg", "BogotaNight.jpg", "farol-da-barra-salvador.jpg"]
    end

  def about_params
    if params[:color] == nil
      @color = 'orange'
    else
      @color = params[:color] 
      end 
    @size = params[:shoe_size]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/destinations/_form.html.erb
<%= form_with(model: destination, local: true) do |form| %>
  <% if destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :population %><br>
    <%= form.number_field :population, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :city %>
    <%= form.text_field :city, id: :destination_city, class: "form-control" %>
  </div>
  
  <div class="field form-group">
    <%= form.label "Photo" %><br>
    <%= form.file_field :avatar %>
  </div>
  
  <div class="field form-group">
    <%= form.label :country %>
    <%= form.text_field :country, id: :destination_country, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :destination_description, class: "form-control", rows: "5" %>
  </div>

  <div class="actions form-group">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form', destination: @destination %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </p>
<% end %>

<ul class="nav nav-pills" role="tablist">
  <li><%= link_to "All", destinations_path %></li>
  <% @my_countries.each do |c| %>
    <li><%= link_to "#{c.country}", controller: "destinations", country: "#{c.country}" %></li>
  <% end %>
</ul>


<h1>My Destination Wish List</h1>

  <div class="row">
    <% @destinations.each do |destination| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
         <h2><%= destination.city %></h2>
         <h3><%= destination.country %></h3>
         <%= image_tag destination.avatar.url(:medium), class: "img-responsive"%>
         <p>Population <%= destination.population %></p>
         <p><%= destination.description %></p>

       
         <div class="btn-group">
          <%= link_to 'Show', destination, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_destination_path(destination), class: "btn btn-default" %>
          <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Destination', new_destination_path, class: "btn btn-primary" %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form', destination: @destination %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @destination.city %>, <%= @destination.country %></h1>

<p> <%= @destination.description %></p>

<%= image_tag @destination.avatar.url %>

<h1><%= @destination.city %>, <%= @destination.country %></h1>
<h2>Population <%= @destination.population %></h2>

<div class="btn-group">
  <%= link_to 'Edit', edit_destination_path(@destination), class: "btn btn-default" %> 
  <%= link_to 'Back', destinations_path, class: "btn btn-default" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel2</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Marck+Script' rel='stylesheet' type='text/css'>
  </head>

  <body>
   <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <%= link_to 'Travel', root_path, class: "navbar-brand" %>
        </div>

       <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Params', params_path %></li>
            <li><%= link_to 'Destinations', destinations_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  <div class= "container">
    <%= yield %>
  </div>
   
</body>
</html>

app/views/welcom/about_params.html.erb
<style>
  body {
    background: <%= @color %>;
  }
  </style>
<h1>Passing params from view to controller</h1>
<h3>My favorite color is <%= @color %>!</h3>
<h3>My shoe size is <%= @size %>!</h3>

<%if @size.to_i >= 12%>
  <h3>I have HUGE feet!</h3>
<%else%>
  <h3>I have an average size foot!</h3>
  <% end %>
 
  <%= link_to "Blue", params_path(color: "blue"), class: "btn btn-primary" %>
  <%= link_to "Red", params_path(color: "red"), class: "btn btn-danger" %>

 <h3><%= link_to 'Index', index_path, class: 'navbar-brand' %></h3>

app/views/welcom/index.html.erb
<h1>Welcom#index</h1>
<p>Find me in app/views/welcom/index.html.erb</p>

<%= @homeland %>
<ul>
  <% @countries.each do |country| %>
<li><%= country %></li>
<% end %>
</ul>

  <%= @travel_pictures.each do |picture|%>
  <ul><%= image_tag picture,  height: 300,
                          width: 400,
                          style: 'border-bottom: 30px', 
                          class: "img-responsive" %></ul>
  <% end %>


<h3><%= link_to 'Params', params_path, class: 'navbar-brand' %>